### ISSUE TITLE
M-Bus registry may be out of sync

### ISSUE THREAD

**Issue by troglobit** [addiva-elektronik/zephyr-mbus-module#2]
Example of restarting an mbus-device instance (so it comes back up with primary address 5):

```
uart:~$ mbus status 
M-Bus module initialized, mbus0 ready for commands.
UART 2400 8N1
PRI  SEC ==============================================
  7  1234567824400107
uart:~$ 
```

Here, the problem is obviously in the M-Bus device node, that it didn't properly remember its new primary address.  However, this begs the question if this is an error state an M-Bus master should take into consideration -- "what if someone has reprogrammed devices, or devices have lost the programming?"  Maybe we need to have a best-before-date in the registry?

Or ... maybe we should never use primary addresses at all, always access devices via indirect addressing (via their secondary address)?

**Comment by hno-wires** [comment]
Fixed in mbus_fixes
